<?php
//$obj->PageHeading("Photo Gallery");

$eventID = $this->getRequest()->getParam('id');
$eventTitle= $this->getCurrentProfile()->getTitle();
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$table = 'events_media_gallery';
$query = 'SELECT file FROM ' . $table . ' WHERE events_id = '
			 . (int)$eventID ;
	/**
	 * Execute the query and store the results in $results
	 */
	$results = $readConnection->fetchCol($query);
	
	/**
	 * Execute the query and store the result in $sku
	 */
	//$sku = $readConnection->fetchOne($query);
//$eventTitle = Mage::getModel('events/events')->load($eventID)->getTitle();
?>
<div class="container">
<div class="row">
<div class="col-md-12 product-list">
	<h2 class="events-heading">Photo Gallery</h2>
	<div class="easy-box">
	<div class="row">
		 <div class="col-md-12" style="padding:20px;"><a href="<?php echo Mage::getUrl('events/index/index');?>" class="blue_text">Event</a><span class="gallerylink2"> &gt;&gt; <strong><?php echo $eventTitle ?></strong></span></div>
	                           									
										<?php foreach($results as $result):?>	
										<div></div>
										<?php 
										 $basePath = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . '/profileimages/events' . $result;
										 //$image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $path;
										?>
																				
									
										<div class="col-md-3">
											<a href="<?php echo $basePath ?>" class="manual2" rel="example_group">
												<img src="<?php echo $basePath ?>" border="0" width="150px" height="100px" class="HoverBorder">
											</a>
										</div>
									        
																				
									     <?php endforeach;?>
							
									        
																				<div>
																				</div>
					
			</div></div>				 
	  </div>
</div>
</div>