<?php
/**
 * New Page template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
$newProducts = $this->_getProductCollection();
?>
<section class="greyBg">
    <div class="container-fluid">
        <h2 class="text-center new-title">Latest Products</h2>
        <div class="latest-product owl-carousel">
            <?php foreach($newProducts as $newProduct) : ?>
                <div class="item">
                    <a href="<?php echo $newProduct->getProductUrl();?>" class="displayBlock">
                        <img src="<?php echo Mage::helper('catalog/image')->init($newProduct, 'thumbnail')->resize(200,200)?>" alt="<?php echo $newProduct->getName(); ?>"/>
                    </a>
                    <p>
                    <a class="product-name" href="<?php echo $newProduct->getProductUrl();?>">
                        <?php echo $newProduct->getName(); ?>
                    </a>
					<?php echo $this->getPriceHtml($newProduct, true); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>