<?php
$featuredProducts = Mage::getModel('catalog/product')->getCollection()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('status',1)
    ->addAttributeToFilter('visibility',4)
    ->addAttributeToFilter('featured', 1);
?>
<section class="greyBg">
    <div class="container-fluid">
        <h2 class="text-center feature-title">Feature Products</h2>
        <div class="featured-product owl-carousel">
            <?php foreach($featuredProducts as $featuredProduct) : ?>
                <div class="item">
                    <a href="<?php echo $featuredProduct->getProductUrl();?>" class="displayBlock">
                        <img src="<?php echo Mage::helper('catalog/image')->init($featuredProduct, 'thumbnail')->resize(200,200)?>" alt="<?php echo $featuredProduct->getName(); ?>"/>
                    </a>
                    <p><?php echo $featuredProduct->getName(); ?>
					<?php echo $this->getPriceHtml($featuredProduct, true); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
	</section>