<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_SeoRichData
 */
?>
<meta name="twitter:card" content="product">
<meta name="twitter:title" content="<?php echo $this->escapeHtml($this->getProduct()->getName()); ?>">
<meta name="twitter:description" content="<?php echo $this->getDescription() ?>">
<meta name="twitter:image" content="<?php echo $this->getResizedImage() ?>">
<meta name="twitter:site" content="<?php echo $this->escapeHtml(Mage::getStoreConfig('amseorichdata/twitter/twitter_account')); ?>">
<meta name="twitter:data1" content="<?php echo $this->escapeHtml($this->getData1()) ?>">
<meta name="twitter:label1" content="<?php echo $this->escapeHtml($this->getLabel1()) ?>">
<meta name="twitter:data2" content="<?php echo $this->escapeHtml($this->getData2()) ?>">
<meta name="twitter:label2" content="<?php echo $this->escapeHtml($this->getLabel2()) ?>">